const OPCODES = {
  0: { name: 'POW', type: 'binop', op: '^' },
  1: { name: 'NEQ', type: 'binop', op: '~=' },
  2: { name: 'TEST_FALSE_JMP', type: 'cond_jmp', cond: 'not' },
  3: { name: 'SETTABLE', type: 'settable' },
  4: { name: 'CALL_MULTI', type: 'call' },
  5: { name: 'NOT', type: 'unop', op: 'not' },
  6: { name: 'GETTABLE', type: 'gettable' },
  7: { name: 'DIV', type: 'binop', op: '/' },
  8: { name: 'SETTABLE_KVAL', type: 'settable' },
  9: { name: 'FORLOOP', type: 'forloop' },
  10: { name: 'FORLOOP', type: 'forloop' },
  11: { name: 'SELF', type: 'self' },
  12: { name: 'CALL_NO_RET', type: 'call' },
  13: { name: 'LOADK', type: 'loadk' },
  14: { name: 'GETTABLE', type: 'gettable' },
  15: { name: 'SETTABLE', type: 'settable' },
  16: { name: 'CALL_VARARG', type: 'call' },
  17: { name: 'SETLIST', type: 'setlist' },
  18: { name: 'CLOSURE', type: 'closure' },
  19: { name: 'SELF', type: 'self' },
  20: { name: 'CONCAT', type: 'binop', op: '..' },
  21: { name: 'CALL_0', type: 'call' },
  22: { name: 'RETURN_1', type: 'return' },
  23: { name: 'GETTABLE', type: 'gettable' },
  24: { name: 'LOADNIL_MULTI', type: 'loadnil' },
  25: { name: 'FORPREP', type: 'forprep' },
  26: { name: 'LOADCONST', type: 'loadk' },
  27: { name: 'SELF', type: 'self' },
  28: { name: 'SETTABLE', type: 'settable' },
  29: { name: 'CLOSURE', type: 'closure' },
  30: { name: 'MOVE', type: 'move' },
  31: { name: 'SELF', type: 'self' },
  32: { name: 'ADD', type: 'binop', op: '+' },
  33: { name: 'NEWTABLE', type: 'newtable' },
  34: { name: 'CALL_2', type: 'call' },
  35: { name: 'MOVE_MULTI', type: 'move' },
  36: { name: 'TEST_TRUE_JMP', type: 'cond_jmp', cond: '' },
  37: { name: 'LOADCONST', type: 'loadk' },
  38: { name: 'LOAD_INST', type: 'misc' },
  39: { name: 'GETTABLE', type: 'gettable' },
  40: { name: 'JMP_REG', type: 'jmp' },
  41: { name: 'CALL_1_NO_RET', type: 'call' },
  42: { name: 'JMP', type: 'jmp' },
  43: { name: 'GETUPVAL', type: 'getupval' },
  44: { name: 'GETGLOBAL', type: 'getglobal' },
  45: { name: 'LOADK_MULTI', type: 'loadk' },
  46: { name: 'CLOSE', type: 'close' },
  47: { name: 'GETTABLE', type: 'gettable' },
  48: { name: 'RETURN_0', type: 'return' },
  49: { name: 'LEN', type: 'unop', op: '#' },
  50: { name: 'NOT', type: 'unop', op: 'not' },
  51: { name: 'CALL_1', type: 'call' },
  52: { name: 'LOADCONST', type: 'loadk' },
  53: { name: 'NEWTABLE', type: 'newtable' },
  54: { name: 'GETTABLE', type: 'gettable' },
  55: { name: 'CALL_N', type: 'call' },
};

function getOpcodeInfo(op) {
  return OPCODES[op] || { name: 'UNKNOWN_' + op, type: 'unknown' };
}

module.exports = {
  OPCODES,
  getOpcodeInfo,
};